---
  - name: Install Packages with latest version on Ubuntu/Debian
    apt:
      name:
        - curl
        - openssl
        - dmidecode

  - name: Install Packages with latest version on Ubuntu/Debian
    apt:
      name:
       - unzip
       - cpio
       - sed
       - lsof
       - rpm
  - name: sysctl_ipv6_enable
    sysctl:
       name: net.ipv6.conf.all.disable_ipv6
       value: '0'
       state: absent

  - name: sysctl_ipv6_enable_default
    sysctl:
       name: net.ipv6.conf.default.disable_ipv6
       value: '0'
       state: absent
